<?php
/**
 * Created by PhpStorm.
 * User: Etudiant
 * Date: 07/03/2018
 * Time: 10:20
 */

namespace App\Controller ;
use App\Entity\Slider;
use Doctrine\DBAL\Connection;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Validator\Constraints\NotBlank;

class AdminController extends Controller
{
    public function admin(Connection $db)
    {
        $articles = $db->fetchAll('SELECT * from article');
        $slider = $db->fetchAll('SELECT * from slider');
        return $this->render('admin.html.twig', [
            'articles' => $articles,
            'sliders' => $slider
        ]);

    }


    public function login(Request $request, AuthenticationUtils $authUtils)
    {
        // get the login error if there is one
        $error = $authUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authUtils->getLastUsername();

        return $this->render('login.html.twig', array(
            'last_username' => $lastUsername,
            'error'         => $error,
        ));
    }

    public function insertSlider(Request $request)
    {

        $slider = new Slider();
        $form = $this->createFormBuilder($slider)

            ->add('libelle', TextType::class, [
                'required'  => false,
                'label'     => false,
                'constraints' => [new NotBlank()],
                'attr'      => [
                    'name'  => 'libelle',
                    'class' => 'form-control' ,
                    'placeholder' => 'titre de l\'image...'
                ]
            ])

            ->add('image', FileType::class, [
                'required'   => true ,
                'label'     => false ,
                'attr'     => [
                    'name'  => 'image',
                    'class'   => 'dropify'
                ]
            ])

            ->add('active', CheckBoxType::class,[
                'required'  => false,
                'label'     => false,
                'attr'      => [
                    'name'  => 'active',
                    'class' => 'form-control' ,
                    'placeholder' => 'description de l\'article...'
                ]
            ])

            ->getForm();
        //$request = Request::createFromGlobals();
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $data = $form->getData();
            $file = $form['image']->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $slider = $form->getData();
            $file = $slider->getImage();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                '../public/images/',
                $fileName);
            $slider->setImage('images/'.$fileName);
            $entityManager->persist($slider);
            $entityManager->flush();


            return $this->render('admin/slider/ajouter.html.twig',[
                'form' =>$form->createView(), 'data'=>$form
            ]);
        }


        return $this->render('admin/slider/ajouter.html.twig',[
            'form' =>$form->createView(), 'data'=>''
        ]);
    }
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    public function insertarticle(Request $request)
    {
        $form = $this->createFormBuilder()
        ->add('titre_article', TextType::class, [
            'required'  => true,
            'label'     => false,
            'constraints' => [new NotBlank()],
            'attr'      => [
                'class' => 'form-control' ,
                'placeholder' => 'titre de l\'article...'
                        ]
                                                ])
            ->add('description', TextType::class,[

                'required'  => true,
                'label'     => false,
                'constraints' => [new NotBlank()],
                'attr'      => [
                    'class' => 'form-control' ,
                    'placeholder' => 'description de l\'article...'
                ]
            ])
            ->add('image', FileType::class, [
                'required'   => false ,
                'label'     => false ,
                'attr'     => [
                    'class'   => 'dropify'
                ]
            ])
        ->getForm();
        $form->handleRequest($request);

        return $this->render('admin/article/ajouter.html.twig',[
            'form' =>$form->createView(), 'data'=>$form
        ]);
    }

}
