app_lucky_number:
    path: /accueil
    controller: App\Controller\LuckyController::affichage

app_contact:
     path: /contact
     controller: App\Controller\contactController::contact

app_articles:
    path: /articles
    controller: App\Controller\ArticlesController::article


login:
    path: /login
    controller: App\Controller\AdminController::login

app_admin:
  path: /admin
  controller: App\Controller\AdminController::admin

app_insertSlider:
    path: /admin/slider/ajouter
    controller: App\Controller\AdminController::insertSlider

app_addarticle:
  path: /admin/article/ajouter
  controller: App\Controller\AdminController::insertarticle


app_description:
  path: /admin/description/modifier
  controller: App\Controller\AdminController::modifier

modif_img:
    path:     /admin/slider/{id}
    controller: App\Controller\AdminController::modifImg

modif_article:
    path:     /admin/article/edit/{id}
    controller: App\Controller\AdminController::modifArticle

supprim_article:
    path:     /admin/article/delete/{id}
    controller: App\Controller\AdminController::supprimArticle



logout:
    path: /logout

