app_lucky_number:
    path: /accueil
    controller: App\Controller\LuckyController::affichage

app_contact:
     path: /contact
     controller: App\Controller\contactController::affichage

app_articles:
    path: /articles
    controller: App\Controller\ArticlesController::article


login:
    path: /login
    controller: App\Controller\AdminController::login

app_admin:
  path: /admin
  controller: App\Controller\AdminController::admin

app_insertSlider:
    path: /admin/slider/ajouter
    controller: App\Controller\AdminController::insertSlider

app_addarticle:
  path: /admin/article/ajouter
  controller: App\Controller\AdminController::insertarticle

<<<<<<< HEAD
app_description:
  path: /admin/description/modifier
  controller: App\Controller\AdminController::modifier


=======
modif_img:
    path:     /admin/slider/{id}
    controller: App\Controller\AdminController::modifImg
>>>>>>> cc6960eaafa9774535f03ac1c7071394ad172a7d


logout:
    path: /logout

