app_lucky_number:
    path: /accueil
    controller: App\Controller\LuckyController::affichage

app_contact:
     path: /contact
     controller: App\Controller\contactController::affichage

app_articles:
    path: /articles
    controller: App\Controller\ArticlesController::article

login:
    path: /login
    controller: App\Controller\AdminController::login

app_admin:
  path: /admin
  controller: App\Controller\AdminController::admin

app_insertSlider:
    path: /admin/slider/ajouter
    controller: App\Controller\AdminController::insertSlider

app_deleteSlider:
    path: /admin/slider/supprimer/{id}
    controller: App\Controller\AdminController::deleteSlider

app_activSlider:
    path: /admin/slider/activ/{id}
    controller: App\Controller\AdminController::activSlider

app_addarticle:
  path: /admin/article/ajouter
  controller: App\Controller\AdminController::insertarticle

app_description:
  path: /admin/description/modifier/
  controller: App\Controller\AdminController::modifier

app_addcontact:
  path: /admin/contact/modifier
  controller: App\Controller\AdminController::contact

logout:
    path: /logout

