app_lucky_number:
    path: /accueil
    controller: App\Controller\LuckyController::affichage

app_contact:
     path: /contact
     controller: App\Controller\contactController::affichage

app_articles:
    path: /articles
    controller: App\Controller\ArticlesController::affichage


app_admin:
    path: /admin
    controller: App\Controller\AdminController::yo

logout:
    path: /logout
