app_lucky_number:
    path: /accueil
    controller: App\Controller\LuckyController::affichage

app_contact:
     path: /contact
     controller: App\Controller\contactController::affichage

app_articles:
    path: /articles
    controller: App\Controller\ArticlesController::article


login:
    path: /login
    controller: App\Controller\AdminController::login

app_admin:
  path: /admin
  controller: App\Controller\AdminController::admin



app_sliderinsert:
    path: /slider
    controller: App\Controller\sliderController::insertslider



logout:
    path: /logout

